---
- hosts: all
  become: true
# To become as root user become=true
#  become: true  
# sudo: yes

  tasks: 
   - name: Install Apache.
     yum: 
       name: 
         - httpd
       state: present
 
   - name: Copy default html file for site. 
     tags: httpd
     copy: 
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

   - name: Make sure Apache is started and configure it to run as boot.
     service: 
       name: httpd 
       state: started 
       enabled: yes
